import { CaseStatus, CaseStage, AssignmentGroup, PrismaClient } from '@prisma/client';
import dayjs from 'dayjs';

const prisma = new PrismaClient();

async function main() {
  await prisma.actionLog.deleteMany();
  await prisma.ruleDecision.deleteMany();
  await prisma.case.deleteMany();
  await prisma.loan.deleteMany();
  await prisma.customer.deleteMany();

  // 1. Create a larger set of customers (25)
  const customersData = Array.from({ length: 25 }).map((_, i) => ({
    name: `Customer ${i + 1}`,
    phone: `+91-98${String(i).padStart(8, '0')}`,
    email: `customer${i + 1}@example.com`,
    country: i % 5 === 0 ? 'US' : 'IN',
    riskScore: Math.floor(Math.random() * 800) + 1 // Risk score 1-800
  }));

  const customers = await prisma.customer.createManyAndReturn({
    data: customersData
  });

  // 2. Create Loans and Cases dynamically
  for (const customer of customers) {
    const isActive = Math.random() > 0.2; // 80% active loans
    const daysOverdue = Math.floor(Math.random() * 60); // 0 to 60 days overdue
    const principal = Math.floor(Math.random() * 500000) + 10000;
    
    const loan = await prisma.loan.create({
      data: {
        customerId: customer.id,
        principal,
        outstanding: Math.floor(principal * (Math.random() * 0.5 + 0.5)),
        dueDate: dayjs().subtract(daysOverdue, 'day').toDate(),
        status: isActive ? 'ACTIVE' : 'CLOSED'
      }
    });

    // Only create cases for active loans with some DPD or random chance
    if (isActive && daysOverdue > 0) {
      let stage: CaseStage = CaseStage.SOFT;
      let group: AssignmentGroup = 'Tier1';
      let assignedTo = 'Tier1Queue';

      if (daysOverdue > 30) {
        stage = CaseStage.LEGAL;
        group = 'Legal';
        assignedTo = 'LegalDesk';
      } else if (daysOverdue > 7) {
        stage = CaseStage.HARD;
        group = 'Tier2';
        assignedTo = 'Tier2Queue';
      }

      // Risk score override logic simulation
      if (customer.riskScore > 750 && stage !== CaseStage.LEGAL) {
        assignedTo = 'SeniorAgent';
      }

      const caseRecord = await prisma.case.create({
        data: {
          customerId: customer.id,
          loanId: loan.id,
          dpd: daysOverdue,
          stage,
          status: Math.random() > 0.8 ? CaseStatus.RESOLVED : CaseStatus.OPEN,
          assignmentGroup: group,
          assignedTo,
          version: 1
        }
      });

      // Add some random actions
      if (Math.random() > 0.5) {
        await prisma.actionLog.create({
          data: {
            caseId: caseRecord.id,
            type: Math.random() > 0.5 ? 'CALL' : 'SMS',
            outcome: Math.random() > 0.7 ? 'PROMISE_TO_PAY' : 'NO_ANSWER',
            notes: 'Generated by seed script'
          }
        });
      }
      
      // Add a rule decision record for audit
      await prisma.ruleDecision.create({
        data: {
          caseId: caseRecord.id,
          matchedRules: ['SEED_GENERATED'],
          reason: `Auto-generated seed: dpd=${daysOverdue}, score=${customer.riskScore}`,
          decisionKey: `seed-auto-${caseRecord.id}`
        }
      });
    }
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
